[package]
name = "pingwin_fun"
version = "0.1.0"
description = "Pingwin.fun bonding-curve launch MVP"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "pingwin_fun"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
