[toolchain]
anchor_version = "0.30.1"

[features]
seeds = true
skip-lint = false

[programs.localnet]
pingwin_fun = "PWin111111111111111111111111111111111111111"

[programs.devnet]
pingwin_fun = "PWin111111111111111111111111111111111111111"

[programs.mainnet]
pingwin_fun = "PWin111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn --cwd .. test:anchor"
